name: Override Settings.xml

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # - uses: actions/setup-java@v3
    #   with:
    #     distribution: 'temurin' # See 'Supported distributions' for available options
    #     java-version: '17'
    - name: debug
      run: |
        ls -al ~
        touch ~/.m2/settings.xml
        ls -al ~/.m2
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'
    - name: debug
      run: |
        ls -al ~/.m2
        cat ~/.m2/settings.xml
