name: Override Settings.xml

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'
    - name: override settings.xml
      run: |
        ls -al ~/.m2 
        rm -rf ~/.m2/settings.xml
        ls -al ~/.m2
        touch ~/.m2/settings.xml
        ls -al ~/.m2
      
